name: dart_writer
version: 0.0.1

description: >-
  Dart code generation
homepage: https://github.com/ahm3tcelik/dart_writer

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dart_style: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0